### PR TITLE
fix: do not return "next" if following page is empty

### PR DESCRIPTION
**Pull request by kpudlik**

### CODE REVIEW

**Review by marcinwadon — DISMISSED** [review]
where `maxSizeLimit` is specified?

**Comment by marcinwadon** [comment]
ah okay. I see it, it's 10k. Is it okay to specify it in the query to be 10k+1?

**Comment by kpudlik** [comment]
> ah okay. I see it, it's 10k. Is it okay to specify it in the query to be 10k+1?

I think we are fine because according to docs `search_after` based pagination is not hard-limited to 10k.

Here are the settings from OpenSearch:

image

Also:

image

**Comment by kpudlik** [comment]
> > ah okay. I see it, it's 10k. Is it okay to specify it in the query to be 10k+1?
> 
> I think we are fine because according to docs `search_after` based pagination is not hard-limited to 10k.

But we can always make it 9999 I think

**Review by marcinwadon — APPROVED** [review]

**Pull request merged**
